######################################################################
# Automatically generated by qmake (3.0) ?? 12? 7 20:15:30 2023
######################################################################

TEMPLATE = app
TARGET = exp301
INCLUDEPATH += .
QT+=widgets
# Input
SOURCES += hello.cpp
