######################################################################
# Automatically generated by qmake (3.0) ?? 12? 8 04:59:59 2023
######################################################################

TEMPLATE = app
TARGET = exp302
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION,4):QT+=widgets
# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
