######################################################################
# Automatically generated by qmake (3.0) ?? 12? 8 08:13:39 2023
######################################################################

TEMPLATE = app
TARGET = exp402
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION,4):QT+=widgets
# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
