######################################################################
# Automatically generated by qmake (3.0) ?? 12? 8 05:19:44 2023
######################################################################

TEMPLATE = app
TARGET = exp401
INCLUDEPATH += .
QT+=widgets
# Input
HEADERS += analogclock.h
SOURCES += analogclock.cpp main.cpp
