######################################################################
# Automatically generated by qmake (3.0) ?? 12? 8 04:50:09 2023
######################################################################

TEMPLATE = app
TARGET = exp303
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION,4):QT+=widgets
# Input
HEADERS += button.h calculator.h
SOURCES += button.cpp calculator.cpp main.cpp
