######################################################################
# Automatically generated by qmake (3.0) ?? 12? 8 08:03:51 2023
######################################################################

TEMPLATE = app
TARGET = exp403
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION,4):QT+=widgets
# Input
HEADERS += mainwindow.h trafficlight.h
SOURCES += main.cpp mainwindow.cpp trafficlight.cpp
