######################################################################
# Automatically generated by qmake (3.0) ?? 12? 13 11:02:42 2023
######################################################################

TEMPLATE = app
TARGET = exp3021
INCLUDEPATH += .
QT+=widgets
# Input
HEADERS += dialog.h wigglywidget.h
SOURCES += dialog.cpp main.cpp wigglywidget.cpp
